CREATE TABLE IF NOT EXISTS REPORTS (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL UNIQUE,
    TYPE TEXT NOT NULL,
    STATUS TEXT,
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    USER_ID INTEGER,
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
)